var fs = require("fs");
var MarkdownIt = require("markdown-it");
var htmlMinifier = require("html-minifier");

var g_md = new MarkdownIt({ "html": true });
var g_htmlMinifyOptions = {
  "collapseInlineTagWhitespace": true,
  "collapseWhitespace": true,
  "conservativeCollapse": true,
  "includeAutoGeneratedTags": false,
  "minifyCSS": true,
  "removeComments": true,
  "removeEmptyAttributes": true,
  "removeEmptyElements": true,
  "removeRedundantAttributes": true
};

function strstr(text, a, b) {
   return text.split(a).join(b);
}

function writeFile(filepath, data) {
  if (!fs.existsSync(filepath)) {
    // create missing directories recursively
    var target = filepath.substr(0, filepath.lastIndexOf("/"));
    fs.mkdirSync(target, { "recursive": true });
  }

  fs.writeFileSync(filepath, data);
}

function readFile(filepath) {
  return fs.readFileSync(filepath).toString();
}

function mdToHtml(markdown) {
  return g_md.render(markdown);
}

function minifyHtml(html) {
  return htmlMinifier.minify(html, g_htmlMinifyOptions);
}

module.exports = {
  strstr,
  writeFile,
  readFile,
  mdToHtml,
  minifyHtml
};
